export const Movies = [{
        id: 1,
        title: "The God Father-1(1972)",
        img: "https://cfm.yidio.com/images/movie/4439/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/238/the-godfather",


    },
    {
        id: 2,
        title: "The God Father-2(1974)",
        img: "https://cfm.yidio.com/images/movie/4889/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/240/the-godfather-part-ii",

    },
    {
        id: 3,
        title: "The God Father-3(1990)",
        img: "https://cfm.yidio.com/images/movie/11441/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/242/the-godfather-part-iii",
    },
    {
        id: 4,
        title: "The Shawshank Redemption(1994)",
        img: "https://cfm.yidio.com/images/movie/13795/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/278/the-shawshank-redemption",
    },
    {
        id: 5,
        title: "the Good the Bad and the Ugly(1996)",
        img: "https://cfm.yidio.com/images/movie/2061/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/429/il-buono-il-brutto-il-cattivo",
    },
    {
        id: 6,
        title: "Braveheart(1995)",
        img: "https://cfm.yidio.com/images/movie/13985/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/197/braveheart",
    },
    {
        id: 7,
        title: "Gladiator(2000)",
        img: "https://cfm.yidio.com/images/movie/17652/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/98/gladiator",
    },
    {
        id: 8,
        title: "300(2006)",
        img: "https://cfm.yidio.com/images/movie/25994/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/1271/300",
    },
    {
        id: 9,
        title: "Jurassic Park(1993)",
        img: "https://cfm.yidio.com/images/movie/13055/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/329/jurassic-park",
    },
    {
        id: 10,
        title: "Forrest Gump(1994)",
        img: "https://cfm.yidio.com/images/movie/13529/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/13/forrest-gump",
    },
    {
        id: 11,
        title: "Gone with the Wind(1939)",
        img: "https://cfm.yidio.com/images/movie/31449/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/770/gone-with-the-wind",
    },
    {
        id: 12,
        title: "Her(2013)",
        img: "https://cfm.yidio.com/images/movie/40647/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/152601/her",
    },
    {
        id: 13,
        title: " Indiana Jones and the Raiders of the Lost Ark(1981)",
        img: "https://cfm.yidio.com/images/movie/45461/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/85/raiders-of-the-lost-ark",
    },
    {
        id: 14,
        title: "Indiana Jones and the Temple of Doom(1984)",
        img: "https://cfm.yidio.com/images/movie/45462/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/87/indiana-jones-and-the-temple-of-doom",
    },
    {
        id: 15,
        title: "Indiana Jones and the Last Crusade(1989)",
        img: "https://cfm.yidio.com/images/movie/45460/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/89/indiana-jones-and-the-last-crusade",
    },
    {
        id: 16,
        title: "Indiana Jones and the Kingdom of the Crystal Skull(2008)",
        img: "https://cfm.yidio.com/images/movie/28347/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/217/indiana-jones-and-the-kingdom-of-the-crystal-skull",
    },
    {
        id: 17,
        title: "Interstellar(2014)",
        img: "https://cfm.yidio.com/images/movie/42499/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/157336/interstellar",
    },
    {
        id: 18,
        title: "Into The Wild(2007)",
        img: "https://cfm.yidio.com/images/movie/26737/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/5915/into-the-wild",
    },
    {
        id: 19,
        title: "Peaceful Warrior(2006)",
        img: "https://cfm.yidio.com/images/movie/25429/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/13689/peaceful-warrior",
    },
    {
        id: 20,
        title: "Scarface(1983)",
        img: "https://cfm.yidio.com/images/movie/34531/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/111/scarface",
    },
    {
        id: 21,
        title: "Schindlers List(1993)",
        img: "https://cfm.yidio.com/images/movie/13208/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/424/schindlers-list",
    },
    {
        id: 22,
        title: "The Curious Case of Benjamin Button(2008)",
        img: "https://cfm.yidio.com/images/movie/27992/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/4922/the-curious-case-of-benjamin-button",
    },
    {
        id: 23,
        title: "The Matrix(1999)",
        img: "https://cfm.yidio.com/images/movie/16975/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/603/the-matrix",
    },
    {
        id: 24,
        title: "The Notebook(2004)",
        img: "https://cfm.yidio.com/images/movie/25365/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/11036/the-notebook",
    },
    {
        id: 25,
        title: "The Sound of Music(1965)",
        img: "https://cfm.yidio.com/images/movie/1850/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/15121/the-sound-of-music",
    },
    {
        id: 26,
        title: "The Lord of the Rings: The Fellowship of the Ring(2001)",
        img: "https://cfm.yidio.com/images/movie/18713/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/120/the-lord-of-the-rings-the-fellowship-of-the-ring",
    },
    {
        id: 27,
        title: "The Lord of the Rings:The Two Towers(2002)",
        img: "https://cfm.yidio.com/images/movie/19721/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/121/the-lord-of-the-rings-the-two-towers",
    },
    {
        id: 28,
        title: "The Lord of the Rings: The Return of the King(2003)",
        img: "https://cfm.yidio.com/images/movie/20833/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/122/the-lord-of-the-rings-the-return-of-the-king",
    },
    {
        id: 29,
        title: "Pulp Fiction(1994)",
        img: "https://cfm.yidio.com/images/movie/32003/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/680/pulp-fiction",
    },
    {
        id: 30,
        title: "Alien(1979)",
        img: "https://cfm.yidio.com/images/movie/6724/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/348/alien",
    },
    {
        id: 31,
        title: "Fight Club(1999)",
        img: "https://cfm.yidio.com/images/movie/16775/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/550/fight-club",
    },
    {
        id: 32,
        title: "Goodfellas(1990)",
        img: "https://cfm.yidio.com/images/movie/11442/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/769/goodfellas",
    },
    {
        id: 33,
        title: "Life is Beautiful(1997)",
        img: "https://cfm.yidio.com/images/movie/15476/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/637/la-vita-e-bella",
    },
    {
        id: 34,
        title: "City of God(2002)",
        img: "https://cfm.yidio.com/images/movie/19375/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/598/cidade-de-deus",
    },
    {
        id: 35,
        title: "Seven(1995)",
        img: "https://cfm.yidio.com/images/movie/14376/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/807/se7en",
    },
    {
        id: 36,
        title: "American History X (1998)",
        img: "https://cfm.yidio.com/images/movie/15816/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/73/american-history-x",
    },
    {
        id: 37,
        title: "Joker(2019)",
        img: "https://cfm.yidio.com/images/movie/176260/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/475557/joker",
    },
    {
        id: 38,
        title: "The Avengers(2012)",
        img: "https://cfm.yidio.com/images/movie/31997/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/24428/the-avengers",
    },
    {
        id: 39,
        title: "Avengers: Infinity War(2018)",
        img: "https://cfm.yidio.com/images/movie/60155/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/299536/avengers-infinity-war",
    },
    {
        id: 40,
        title: "Avengers: EndGame(2019)",
        img: "https://cfm.yidio.com/images/movie/60156/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/299534/avengers-endgame",
    },
    {
        id: 41,
        title: "The Dark Knight(2008)",
        img: "https://cfm.yidio.com/images/movie/28004/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/155/the-dark-knight",
    },
    {
        id: 42,
        title: "The Dark Knight Rises(2012)",
        img: "https://cfm.yidio.com/images/movie/31853/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/49026/the-dark-knight-rises",
    },
    {
        id: 43,
        title: "Once Upon a Time in Hollywood(2019)",
        img: "https://cfm.yidio.com/images/movie/176261/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/466272/once-upon-a-time-in-hollywood",
    },
    {
        id: 44,
        title: "12 Years A Slave(2013)",
        img: "https://cfm.yidio.com/images/movie/41792/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/76203/12-years-a-slave",
    },
    {
        id: 45,
        title: "Money Ball(2011)",
        img: "https://cfm.yidio.com/images/movie/31622/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/988464/money-ball",
    },
    {
        id: 46,
        title: "Inglorious Basterds(2009)",
        img: "https://tse3.mm.bing.net/th?id=OIP.sUiz68qtvJ-qLITM8JfbfwHaNL&pid=Api&P=0",
        path: "https://moviestreams.club/en/movie/16869/inglourious-basterds",
    },
    {
        id: 47,
        title: "Troy(2004)",
        img: "https://cfm.yidio.com/images/movie/22578/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/652/troy",
    },
    {
        id: 48,
        title: "Titanic(1997)",
        img: "https://cfm.yidio.com/images/movie/15722/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/597/titanic",
    },
    {
        id: 49,
        title: "The Beach(2000)",
        img: "https://cfm.yidio.com/images/movie/17404/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/1907/the-beach",
    },
    {
        id: 50,
        title: "Catch Me If You Can(2002)",
        img: "https://cfm.yidio.com/images/movie/19347/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/640/catch-me-if-you-can",
    },
    {
        id: 51,
        title: "The Aviator(2004)",
        img: "https://cfm.yidio.com/images/movie/21472/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/2567/the-aviator",
    },
    {
        id: 52,
        title: "The Departed(2006)",
        img: "https://cfm.yidio.com/images/movie/24669/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/1422/the-departed",
    },
    {
        id: 53,
        title: "Blood Diamond(2006)",
        img: "https://cfm.yidio.com/images/movie/24449/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/1372/blood-diamond",
    },
    {
        id: 54,
        title: "Revolutionary Road(2008)",
        img: "https://cfm.yidio.com/images/movie/28859/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/4148/revolutionary-road",
    },
    {
        id: 55,
        title: "Shutter Island(2010)",
        img: "https://cfm.yidio.com/images/movie/30249/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/11324/shutter-island",
    },
    {
        id: 56,
        title: "Inception(2010)",
        img: "https://cfm.yidio.com/images/movie/30588/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/27205/inception",
    },
    {
        id: 57,
        title: "Jaws(1975)",
        img: "https://cfm.yidio.com/images/movie/5289/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/578/jaws",
    },
    {
        id: 58,
        title: "Close Encounters of the Third Kind(1977)",
        img: "https://cfm.yidio.com/images/movie/5973/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/840/close-encounters-of-the-third-kind",
    },
    {
        id: 59,
        title: "E.T. The Extra-Terrestrial(1982)",
        img: "https://cfm.yidio.com/images/movie/140322/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/601/et-the-extra-terrestrial",
    },
    {
        id: 60,
        title: "The Color Purple(1985)",
        img: "https://cfm.yidio.com/images/movie/9294/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/873/the-color-purple",
    },
    {
        id: 61,
        title: "Empire of the Sun(1987)",
        img: "https://cfm.yidio.com/images/movie/9861/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/10110/empire-of-the-sun",
    },
    {
        id: 62,
        title: "Amistad(1997)",
        img: "https://cfm.yidio.com/images/movie/15158/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/11831/amistad",
    },
    {
        id: 63,
        title: "Saving Private Ryan(1998)",
        img: "https://cfm.yidio.com/images/movie/16361/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/857/saving-private-ryan",
    },
    {
        id: 64,
        title: "A.I. Artificial Intelligence(2001)",
        img: "https://cfm.yidio.com/images/movie/18207/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/644/ai-artificial-intelligence",
    },
    {
        id: 65,
        title: "The Terminal(2004)",
        img: "https://cfm.yidio.com/images/movie/22534/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/594/the-terminal",
    },
    {
        id: 66,
        title: "Munich(2005)",
        img: "https://cfm.yidio.com/images/movie/23649/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/612/munich",
    },
    {
        id: 67,
        title: "War Horse(2011)",
        img: "https://cfm.yidio.com/images/movie/31669/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/57212/war-horse",
    },
    {
        id: 68,
        title: "Lincoln(2012)",
        img: "https://cfm.yidio.com/images/movie/37608/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/72976/lincoln",
    },
    {
        id: 69,
        title: "The BFG(2016)",
        img: "https://cfm.yidio.com/images/movie/56737/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/267935/the-bfg",
    },
    {
        id: 70,
        title: "West Side Story(2021)",
        img: "https://cfm.yidio.com/images/movie/199449/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/511809/west-side-story",
    },
    {
        id: 71,
        title: "Resorvoir Dogs(1992)",
        img: "https://cfm.yidio.com/images/movie/12661/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/500/reservoir-dogs",
    },
    {
        id: 72,
        title: "The Wolf of Wall Street(2013)",
        img: "https://cfm.yidio.com/images/movie/39461/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/106646/the-wolf-of-wall-street",
    },
    {
        id: 73,
        title: "The Terminator(1984)",
        img: "https://cfm.yidio.com/images/movie/44425/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/218/the-terminator",
    },
    {
        id: 74,
        title: "Terminator 2: Judgement Day(1991)",
        img: "https://cfm.yidio.com/images/movie/12221/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/280/terminator-2-judgment-day",
    },
    {
        id: 75,
        title: "Avatar(2009)",
        img: "https://cfm.yidio.com/images/movie/29303/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/19995/avatar",
    },
    {
        id: 76,
        title: "Avatar: The Way of Water(2022)",
        img: "https://cfm.yidio.com/images/movie/64679/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/76600/avatar-the-way-of-water",
    },
    {
        id: 77,
        title: "Gone Girl(2014)",
        img: "https://cfm.yidio.com/images/movie/44921/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/210577/gone-girl",
    },
    {
        id: 78,
        title: "The Prestige(2006)",
        img: "https://cfm.yidio.com/images/movie/25474/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/1124/the-prestige",
    },
    {
        id: 79,
        title: "Memento(2000)",
        img: "https://cfm.yidio.com/images/movie/18747/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/77/memento",
    },
    {
        id: 80,
        title: "A beautiful Mind",
        img: "https://cfm.yidio.com/images/movie/18283/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/453/a-beautiful-mind",
    },
    {
        id: 81,
        title: "Cast Away",
        img: "https://cfm.yidio.com/images/movie/17474/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/8358/cast-away",
    },
    {
        id: 82,
        title: "The Blind Side",
        img: "https://cfm.yidio.com/images/movie/30219/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/22881/the-blind-side",
    },
    {
        id: 83,
        title: "The Fighter(2010)",
        img: "https://cfm.yidio.com/images/movie/31117/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/45317/the-fighter",
    },
    {
        id: 84,
        title: "The Theory of Everything(2014)",
        img: "https://cfm.yidio.com/images/movie/46172/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/266856/the-theory-of-everything",
    },
    {
        id: 85,
        title: "Dead Poets Society(1989)",
        img: "https://cfm.yidio.com/images/movie/47716/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/207/dead-poets-society",
    },
    {
        id: 86,
        title: "Coach Carter(2005)",
        img: "https://cfm.yidio.com/images/movie/23011/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/7214/coach-carter",
    },
    {
        id: 87,
        title: "Harry Potter and The Sorcerer's Stone(2001)",
        img: "https://cfm.yidio.com/images/movie/18564/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/671/harry-potter-and-the-philosophers-stone",
    },
    {
        id: 88,
        title: "Harry Potter and The Chamber of Secrets(2002)",
        img: "https://cfm.yidio.com/images/movie/19567/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/672/harry-potter-and-the-chamber-of-secrets",
    },
    {
        id: 89,
        title: "Harry Potter and The Prisoner of Azkaban(2004)",
        img: "https://cfm.yidio.com/images/movie/21867/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/673/harry-potter-and-the-prisoner-of-azkaban",
    },
    {
        id: 90,
        title: "Harry Potter and the Goblet of Fire(2005)",
        img: "https://cfm.yidio.com/images/movie/23302/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/674/harry-potter-and-the-goblet-of-fire",
    },
    {
        id: 91,
        title: "Harry Potter and the Order of the Phoenix(2007)",
        img: "https://cfm.yidio.com/images/movie/26637/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/675/harry-potter-and-the-order-of-the-phoenix",
    },
    {
        id: 92,
        title: "Harry Potter and the Half-Blood Prince(2009)",
        img: "https://cfm.yidio.com/images/movie/29464/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/767/harry-potter-and-the-half-blood-prince",
    },
    {
        id: 93,
        title: "Harry Potter and the Deathly Hallows - Part 1(2010)",
        img: "https://cfm.yidio.com/images/movie/29858/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/12444/harry-potter-and-the-deathly-hallows-part-1",
    },
    {
        id: 94,
        title: "Harry Potter and the Deathly Hallows - Part 2(2011)",
        img: "https://cfm.yidio.com/images/movie/31882/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/12445/harry-potter-and-the-deathly-hallows-part-2",
    },
    {
        id: 95,
        title: "Malena(2000)",
        img: "https://cfm.yidio.com/images/movie/33225/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/10867/malena",
    },
    {
        id: 96,
        title: "Bitter Moon(1992)",
        img: "https://cfm.yidio.com/images/movie/49164/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/10497/bitter-moon",
    },
    {
        id: 97,
        title: "Life of PI",
        img: "https://cfm.yidio.com/images/movie/35243/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/87827/life-of-pi",
    },
    {
        id: 98,
        title: "The Lion King",
        img: "https://cfm.yidio.com/images/movie/127755/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/420818/the-lion-king",
    },
    {
        id: 99,
        title: "A Fistful of Dollars(1964)",
        img: "https://cfm.yidio.com/images/movie/1303/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/391/per-un-pugno-di-dollari",
    },
    {
        id: 100,
        title: "The Jungle Book(2016)",
        img: "https://cfm.yidio.com/images/movie/45761/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/278927/the-jungle-book",

    },
];
export const Series = [{
        id: 1,
        title: "Breaking Bad(2008)",
        img: "https://cfm.yidio.com/images/tv/2006/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/1396/breaking-bad",
    },
    {
        id: 2,
        title: "Game of Thrones(2011)",
        img: "https://cfm.yidio.com/images/tv/5878/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/1399/game-of-thrones",
    },
    {
        id: 3,
        title: "Cursed(2020)",
        img: "https://cfm.yidio.com/images/tv/61815/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/83125/cursed",
    },
    {
        id: 4,
        title: "Dark(2017)",
        img: "https://cfm.yidio.com/images/tv/42250/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/70523/dark",
    },
    {
        id: 5,
        title: "Peaky Blinders(2013)",
        img: "https://cfm.yidio.com/images/tv/26963/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/60574/peaky-blinders",
    },
    {
        id: 6,
        title: "Narcos(2015)",
        img: "https://cfm.yidio.com/images/tv/29129/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/63351/narcos",
    },
    {
        id: 7,
        title: "Sherlock(2010)",
        img: "https://cfm.yidio.com/images/tv/6068/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/19885/sherlock",
    },
    {
        id: 8,
        title: "Friends(1994)",
        img: "https://cfm.yidio.com/images/tv/736/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/1668/friends",
    },
    {
        id: 9,
        title: "Mr. Robot(2015)",
        img: "https://cfm.yidio.com/images/tv/28761/poster-360x540.jpg",
        path: "https://moviestreams.club/en/tv/62560/mr-robot",
    },
    {
        id: 10,
        title: "Life(2007)",
        img: "https://cfm.yidio.com/images/tv/358/poster-360x540.jpg",
        path: "https://moviestreams.club/en/movie/395992/life",
    },
];
export const Images = [{
        id: 1,
        img: "https://www.justwatch.com/images/icon/207360008/s100/icon.webp",
        url: "https://www.netflix.com/in/",
        title: "Netflix",
    },
    {
        id: 2,
        img: "https://www.justwatch.com/images/icon/52449861/s100/icon.webp",
        url: "https://www.primevideo.com/",
        title: "Amazon Prime Video",
    },
    {
        id: 3,
        img: "https://www.justwatch.com/images/icon/240029443/s100/icon.webp",
        url: "https://www.hotstar.com/in",
        title: "Hotstar",
    },
    {
        id: 4,
        img: "https://www.justwatch.com/images/icon/4233119/s100/icon.webp",
        url: "https://www.voot.com/",
        title: "Voot",
    },
    {
        id: 5,
        img: "https://www.justwatch.com/images/icon/85114140/s100/icon.webp",
        url: "https://www.jiocinema.com/",
        title: "Jio Cinema",
    },
    {
        id: 6,
        img: "https://www.justwatch.com/images/icon/93795879/s100/icon.webp",
        url: "https://www.zee5.com/",
        title: "Zee5",
    },
    {
        id: 7,
        img: "https://www.justwatch.com/images/icon/301318462/s100/icon.webp",
        url: "https://www.hayu.com/",
        title: "Hayu",
    },
    {
        id: 8,
        img: "https://images.justwatch.com/icon/152862153/s100/icon.webp",
        url: "https://tv.apple.com/",
        title: "Apple TV Plus",
    },
    {
        id: 9,
        img: "https://images.justwatch.com/icon/190848813/s100/icon.webp",
        url: "https://www.apple.com/itunes/",
        title: "Apple iTunes",
    },
    {
        id: 10,
        img: "https://images.justwatch.com/icon/247912837/s100/icon.webp",
        url: "https://erosnow.com/",
        title: "Eros Now",
    },

    {
        id: 11,
        img: "https://images.justwatch.com/icon/169478387/s100/icon.webp",
        url: "https://play.google.com/store/movies",
        title: "Google Play Movies",
    },
    {
        id: 12,
        img: "https://images.justwatch.com/icon/164970114/s100/icon.webp",
        url: "https://mubi.com/",
        title: "MUBI",
    },
    {
        id: 13,
        img: "https://images.justwatch.com/icon/207468084/s100/icon.webp",
        url: "https://www.sonyliv.com/",
        title: "Sony Liv",
    },
    {
        id: 14,
        img: "https://images.justwatch.com/icon/59562423/s100/icon.webp",
        url: "https://www.youtube.com/",
        title: "YouTube",
    },
    {
        id: 15,
        img: "https://images.justwatch.com/icon/2625277/s100/icon.webp",
        url: "https://guidedoc.tv/",
        title: "GuideDoc",
    },
    {
        id: 16,
        img: "https://images.justwatch.com/icon/14385750/s100/icon.webp",
        url: "https://www.netflix.com/in/browse/genre/783",
        title: "Netflix Kids",
    },
    {
        id: 17,
        img: "https://images.justwatch.com/icon/104966985/s100/icon.webp",
        url: "https://tubitv.com/",
        title: "Tubi TV",
    },
    {
        id: 18,
        img: "https://images.justwatch.com/icon/123324312/s100/icon.webp",
        url: "https://www.yupptv.com/",
        title: "Yupp TV",
    },
    {
        id: 19,
        img: "https://images.justwatch.com/icon/138047862/s100/icon.webp",
        url: "https://www.sunnxt.com/",
        title: "Sun Nxt",
    },
    {
        id: 20,
        img: "https://images.justwatch.com/icon/141253805/s100/icon.webp",
        url: "https://www.hoichoi.tv/",
        title: "Hoichoi",
    },
    {
        id: 21,
        img: "https://images.justwatch.com/icon/141488812/s100/icon.webp",
        url: "https://www.youtube.com/c/ALTBalaji/videos",
        title: "Alt Balaji",
    },
    {
        id: 22,
        img: "https://images.justwatch.com/icon/201704934/s100/icon.webp",
        url: "https://www.hungama.com/",
        title: "Hungama Play",
    },
    {
        id: 23,
        img: "https://images.justwatch.com/icon/48600036/s100/icon.webp",
        url: "https://curiositystream.com/",
        title: "Curiosity Stream",
    },
    {
        id: 24,
        img: "https://images.justwatch.com/icon/208171262/s100/icon.webp",
        url: "https://epicon.com/",
        title: "EPIC ON",
    },
    {
        id: 25,
        img: "https://images.justwatch.com/icon/208147531/s100/icon.webp",
        url: "https://www.shemaroome.com/",
        title: "ShemarooMe",
    },
    {
        id: 26,
        img: "https://images.justwatch.com/icon/208148387/s100/icon.webp",
        url: "https://www.docsville.com/",
        title: "DOCSVILLE",
    },
    {
        id: 27,
        img: "https://images.justwatch.com/icon/209544767/s100/icon.webp",
        url: "https://tvfplay.com/",
        title: "TVF Play",
    },
    {
        id: 28,
        img: "https://images.justwatch.com/icon/286806073/s100/icon.webp",
        url: "https://www.tataplay.com/",
        title: "Tata Play",
    },
    {
        id: 29,
        img: "https://images.justwatch.com/icon/240558410/s100/icon.webp",
        url: "https://www.discoveryplus.in/",
        title: "Discovery Plus",
    },
    {
        id: 30,
        img: "https://images.justwatch.com/icon/208852613/s100/icon.webp",
        url: "https://www.youtube.com/c/ManoramaMAX",
        title: "ManoramaMax",
    },
    {
        id: 31,
        img: "https://images.justwatch.com/icon/207967415/s100/icon.webp",
        url: "https://filmrise.com/",
        title: "FILMRISE",
    },
    {
        id: 32,
        img: "https://images.justwatch.com/icon/210188316/s100/icon.webp",
        url: "https://www.mxplayer.in/",
        title: "MX Player",
    },
    {
        id: 33,
        img: "https://images.justwatch.com/icon/242563117/s100/icon.webp",
        url: "https://www.aha.video/",
        title: "aha",
    },
    {
        id: 34,
        img: "https://images.justwatch.com/icon/430993/s100/icon.webp",
        url: "https://www.amazon.com/Amazon-Video/b?node=2858778011",
        title: "Amazon Video",
    },
    {
        id: 35,
        img: "https://images.justwatch.com/icon/248952863/s100/icon.webp",
        url: "https://moviesandtv.myvi.in/",
        title: "VI movies & tv",
    },
    {
        id: 36,
        img: "https://images.justwatch.com/icon/269959825/s100/icon.webp",
        url: "https://www.filmbox.com/int/home?locale=en-US",
        title: "FilmBox+",
    },

];